### ISSUE TITLE
Did you tried to finetune the model?

### ISSUE THREAD

**Issue by shudong-zhang** [catid/supercharger#1]
Hi, intresting results. Did you tried to finetune the LLM model like miscrosoft codebert? https://github.com/microsoft/CodeXGLUE/tree/main/Code-Code/Defect-detection

**Comment by catid** [comment]
I haven't tried any LLM fine-tuning yet.  Sounds fun, but probably a bridge too far for me.  My goal is more towards being able to train my own very small models at home, so can't afford to get too distracted by LLMs.

**Comment by cyw3** [comment]
Great experimental project.
So what optimization ideas do you have next?
